### ISSUE TITLE
Timers labels are incorrect

### ISSUE THREAD

**Issue by NateNate60** [CrazyPyroEagle/ToS-TextClient#2]
Day 1 timer still shows "start" and is stuck at 30.
Night timer shows either "start" or "voting". If a player was voted up it shows "judgement"
After acquitting a player the timer still shows "judgement" during the remaining voting time.

**Comment by CrazyPyroEagle** [comment]
S#93 (StartNight) didn't update the timer text, causing the timer to stay stuck on the previous phase. Fixed in 1c1bcc8.
