### ISSUE TITLE
Logging in does not work, throws error, but closes before it can be read

### ISSUE THREAD

**Issue by NateNate60** [CrazyPyroEagle/ToS-TextClient#3]
Downloaded the newest version today (18 July), and it appears that the login screen bricks.

[Link.](https://1drv.ms/v/s!AocENoo2Y-KpgYFsM1SdRSotPD6J6A)

**Comment by CrazyPyroEagle** [comment]
I should really have tested for that, I presume you don't have the Steam version installed at the default path?

**Comment by NateNate60** [comment]
I have it installed at D:\Games\Steam Games

I have separate drives for games and files (D:), and the OS (C:).

**Comment by CrazyPyroEagle** [comment]
I've created a [new release](https://github.com/CrazyPyroEagle/ToS-TextClient/releases/tag/v1.4.5.1) that contains the fix.

**Comment by NateNate60** [comment]
It works. Thanks!
