### ISSUE TITLE
[enhancement] allow /slw command is whispers.

### ISSUE THREAD

**Issue by Mustafa-C** [CrazyPyroEagle/ToS-TextClient#8]
/slw should be allowed in whispers since copying is literally impossible.

**Comment by CrazyPyroEagle** [comment]
On some systems, it is possible to select and copy the on-screen text using the mouse cursor.
I will investigate the possibility of making text selections and copying in the input fields using the keyboard.

**Comment by Mustafa-C** [comment]
![image](https://user-images.githubusercontent.com/19622111/43824173-307c0daa-9ae9-11e8-8105-5fe85aa97701.png)
Text selection happens like this on my systems (Windows 10) which makes it impossible to copy my will without getting a lot of lines and chat log in my clipboard too.

**Comment by CrazyPyroEagle** [comment]
Yes, Windows 10 changed selection in cmd.
In the next release, /slw will have a player argument to give the option of whispering.
